// Code generated by MockGen. DO NOT EDIT.
// Source: go-secretshelper/pkg/core (interfaces: SinkWriterPort)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	core "go-secretshelper/pkg/core"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSinkWriterPort is a mock of SinkWriterPort interface.
type MockSinkWriterPort struct {
	ctrl     *gomock.Controller
	recorder *MockSinkWriterPortMockRecorder
}

// MockSinkWriterPortMockRecorder is the mock recorder for MockSinkWriterPort.
type MockSinkWriterPortMockRecorder struct {
	mock *MockSinkWriterPort
}

// NewMockSinkWriterPort creates a new mock instance.
func NewMockSinkWriterPort(ctrl *gomock.Controller) *MockSinkWriterPort {
	mock := &MockSinkWriterPort{ctrl: ctrl}
	mock.recorder = &MockSinkWriterPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSinkWriterPort) EXPECT() *MockSinkWriterPortMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockSinkWriterPort) Write(arg0 context.Context, arg1 *core.Defaults, arg2 *core.Secret, arg3 *core.Sink) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockSinkWriterPortMockRecorder) Write(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockSinkWriterPort)(nil).Write), arg0, arg1, arg2, arg3)
}
