// Code generated by MockGen. DO NOT EDIT.
// Source: go-secretshelper/pkg/core (interfaces: VaultAccessorPort)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	core "go-secretshelper/pkg/core"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockVaultAccessorPort is a mock of VaultAccessorPort interface.
type MockVaultAccessorPort struct {
	ctrl     *gomock.Controller
	recorder *MockVaultAccessorPortMockRecorder
}

// MockVaultAccessorPortMockRecorder is the mock recorder for MockVaultAccessorPort.
type MockVaultAccessorPortMockRecorder struct {
	mock *MockVaultAccessorPort
}

// NewMockVaultAccessorPort creates a new mock instance.
func NewMockVaultAccessorPort(ctrl *gomock.Controller) *MockVaultAccessorPort {
	mock := &MockVaultAccessorPort{ctrl: ctrl}
	mock.recorder = &MockVaultAccessorPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultAccessorPort) EXPECT() *MockVaultAccessorPortMockRecorder {
	return m.recorder
}

// RetrieveSecret mocks base method.
func (m *MockVaultAccessorPort) RetrieveSecret(arg0 context.Context, arg1 *core.Defaults, arg2 *core.Vault, arg3 *core.Secret) (*core.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveSecret", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*core.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveSecret indicates an expected call of RetrieveSecret.
func (mr *MockVaultAccessorPortMockRecorder) RetrieveSecret(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveSecret", reflect.TypeOf((*MockVaultAccessorPort)(nil).RetrieveSecret), arg0, arg1, arg2, arg3)
}
