name: Go

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: '1.x'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Test
        run: |
          go test -v ./... -coverpkg=./...

      - name: Build the Go application
        run: go build -v ./...

      - name: Run linting (golangci-lint)
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0

      - name: Upload coverage results
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
